name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Build
        run: |
          pip install .
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
      - name: Build distributions
        run: |
          pip install setuptools wheel
          python setup.py sdist bdist_wheel